#include <pthread.h>
#include <chrono>
#include <deque>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <thread>
#include <vector>
struct Config{int p=2,c=2,cap=10,n=100,pd=80,cd=120;};
struct Stats{pthread_mutex_t m{};int made=0,taken=0,pwait=0,cwait=0;Stats(){pthread_mutex_init(&m,0);}~Stats(){pthread_mutex_destroy(&m);}};
class Log{pthread_mutex_t m{};std::vector<std::string> e;public:Log(){pthread_mutex_init(&m,0);}~Log(){pthread_mutex_destroy(&m);}void add(std::string x){pthread_mutex_lock(&m);e.push_back(x);std::cout<<x<<'\n';pthread_mutex_unlock(&m);}void clear(){pthread_mutex_lock(&m);e.clear();pthread_mutex_unlock(&m);}void show(){pthread_mutex_lock(&m);for(auto&x:e)std::cout<<x<<'\n';pthread_mutex_unlock(&m);}void save(){pthread_mutex_lock(&m);std::ofstream f("logs/simulation.log");for(auto&x:e)f<<x<<'\n';pthread_mutex_unlock(&m);}};
class Queue{std::deque<std::pair<int,int>> q;int cap;bool done=false;pthread_mutex_t m{};pthread_cond_t full{},empty{};public:Queue(int n):cap(n){pthread_mutex_init(&m,0);pthread_cond_init(&full,0);pthread_cond_init(&empty,0);}~Queue(){pthread_mutex_destroy(&m);pthread_cond_destroy(&full);pthread_cond_destroy(&empty);}void push(std::pair<int,int>x,Stats&s,int&size){pthread_mutex_lock(&m);while((int)q.size()==cap){pthread_mutex_lock(&s.m);++s.pwait;pthread_mutex_unlock(&s.m);pthread_cond_wait(&full,&m);}q.push_back(x);size=q.size();pthread_cond_signal(&empty);pthread_mutex_unlock(&m);}bool pop(std::pair<int,int>&x,Stats&s,int&size){pthread_mutex_lock(&m);while(q.empty()&&!done){pthread_mutex_lock(&s.m);++s.cwait;pthread_mutex_unlock(&s.m);pthread_cond_wait(&empty,&m);}if(q.empty()){pthread_mutex_unlock(&m);return false;}x=q.front();q.pop_front();size=q.size();pthread_cond_signal(&full);pthread_mutex_unlock(&m);return true;}void close(){pthread_mutex_lock(&m);done=true;pthread_cond_broadcast(&empty);pthread_mutex_unlock(&m);}int size(){pthread_mutex_lock(&m);int n=q.size();pthread_mutex_unlock(&m);return n;}};
struct Shared{Queue*q;Stats*s;Log*l;Config cfg;int next=0;pthread_mutex_t m{};Shared(Queue*x,Stats*y,Log*z,Config c):q(x),s(y),l(z),cfg(c){pthread_mutex_init(&m,0);}~Shared(){pthread_mutex_destroy(&m);}};struct Arg{Shared*d;int id;};
void* prod(void*v){auto*a=(Arg*)v;auto&d=*a->d;for(;;){pthread_mutex_lock(&d.m);int x=++d.next;pthread_mutex_unlock(&d.m);if(x>d.cfg.n)break;std::this_thread::sleep_for(std::chrono::milliseconds(d.cfg.pd));int z;d.q->push({x,a->id},*d.s,z);pthread_mutex_lock(&d.s->m);++d.s->made;pthread_mutex_unlock(&d.s->m);d.l->add("[Producer "+std::to_string(a->id)+"] Produced Item #"+std::to_string(x)+" | Buffer: "+std::to_string(z)+"/"+std::to_string(d.cfg.cap));}return 0;}
void* cons(void*v){auto*a=(Arg*)v;auto&d=*a->d;std::pair<int,int>x;int z;while(d.q->pop(x,*d.s,z)){std::this_thread::sleep_for(std::chrono::milliseconds(d.cfg.cd));pthread_mutex_lock(&d.s->m);++d.s->taken;pthread_mutex_unlock(&d.s->m);d.l->add("[Consumer "+std::to_string(a->id)+"] Consumed Item #"+std::to_string(x.first)+" | Buffer: "+std::to_string(z)+"/"+std::to_string(d.cfg.cap));}return 0;}
int ask(const char*x,int cur){std::cout<<x<<" ["<<cur<<"]: ";std::string s;std::getline(std::cin,s);try{return s.empty()?cur:std::stoi(s);}catch(...){return cur;}}
int main(){Config c;Stats st;Log log;std::unique_ptr<Queue> last;double sec=0;bool ran=false;for(;;){std::cout<<"\n=== Producer Consumer Simulator ===\n1. Configure Simulation\n2. Start Simulation\n3. View Statistics\n4. View Activity Log\n5. Reset\n6. Exit\nChoice: ";std::string m;std::getline(std::cin,m);if(m=="1"){c.p=ask("Producer threads",c.p);c.c=ask("Consumer threads",c.c);c.cap=ask("Buffer capacity",c.cap);c.n=ask("Items",c.n);c.pd=ask("Producer delay ms",c.pd);c.cd=ask("Consumer delay ms",c.cd);if(c.p<1||c.p>10||c.c<1||c.c>10||c.cap<1||c.n<1||c.n>10000||c.pd<0||c.cd<0){std::cout<<"Invalid configuration.\n";c=Config{};}}else if(m=="2"){pthread_mutex_lock(&st.m);st.made=st.taken=st.pwait=st.cwait=0;pthread_mutex_unlock(&st.m);log.clear();last=std::make_unique<Queue>(c.cap);Shared d(last.get(),&st,&log,c);std::vector<pthread_t>P(c.p),C(c.c);std::vector<Arg>pa(c.p),ca(c.c);auto start=std::chrono::steady_clock::now();for(int i=0;i<c.c;i++){ca[i]={&d,i+1};pthread_create(&C[i],0,cons,&ca[i]);}for(int i=0;i<c.p;i++){pa[i]={&d,i+1};pthread_create(&P[i],0,prod,&pa[i]);}for(auto&t:P)pthread_join(t,0);last->close();for(auto&t:C)pthread_join(t,0);sec=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();ran=true;log.add("Simulation completed.");log.save();std::cout<<"Saved logs/simulation.log\n";}else if(m=="3"){if(!ran)std::cout<<"No completed simulation.\n";else{pthread_mutex_lock(&st.m);std::cout<<"Produced: "<<st.made<<"\nConsumed: "<<st.taken<<"\nBuffer size: "<<last->size()<<"\nProducer waits: "<<st.pwait<<"\nConsumer waits: "<<st.cwait<<"\nExecution time: "<<sec<<" sec\n";pthread_mutex_unlock(&st.m);}}else if(m=="4")log.show();else if(m=="5"){log.clear();last.reset();ran=false;std::cout<<"Reset complete.\n";}else if(m=="6")break;else std::cout<<"Invalid menu choice.\n";}}
